# Generated by Django 5.0 on 2024-03-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_details',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
