# Generated by Django 5.0 on 2024-01-30 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipphoneapp', '0002_product_tbl'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tbl',
            name='c_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='product_tbl',
            name='stock',
            field=models.IntegerField(null=True),
        ),
    ]
