# Generated by Django 5.0 on 2024-01-30 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipphoneapp', '0003_product_tbl_c_name_product_tbl_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tbl',
            name='product_spec',
            field=models.TextField(null=True),
        ),
    ]
