# Generated by Django 5.0 on 2024-01-31 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipphoneapp', '0005_alter_product_tbl_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_tbl',
            old_name='product_spec',
            new_name='product_Battery',
        ),
        migrations.AddField(
            model_name='product_tbl',
            name='product_Display',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product_tbl',
            name='product_Processor',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product_tbl',
            name='product_Ram',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product_tbl',
            name='product_Rom',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product_tbl',
            name='product_build',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product_tbl',
            name='product_color',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product_tbl',
            name='product_connectivity',
            field=models.TextField(null=True),
        ),
    ]
