# Generated by Django 5.0 on 2024-01-31 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipphoneapp', '0006_rename_product_spec_product_tbl_product_battery_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_tbl',
            old_name='product_color',
            new_name='product_camera',
        ),
    ]
