# Generated by Django 5.0 on 2024-01-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipphoneapp', '0007_rename_product_color_product_tbl_product_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tbl',
            name='product_Operatingsystem',
            field=models.TextField(null=True),
        ),
    ]
