# Generated by Django 5.0 on 2024-02-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flipphoneapp', '0010_product_tbl_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_tbl',
            name='brand',
        ),
    ]
